server:
  port: 8085
spring:
  application:
    name: MyPhotoAppApiGateway
  devtools:
    restart:
      enabled: true
  cloud:
    gateway:
      routes[0]:
        id: users-status-check
        uri: lb://MyPhotoAppApiUsers
        predicates[0]: Path=/users/status/check
        predicates[1]: Method=GET
        filters[0]: RemoveRequestHeader=Cookie
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
